### ISSUE TITLE
Failed to extract span context due to missingSampleDecision

### ISSUE THREAD

**Issue by tachyonics** [slashmo/swift-otel-xray#7]
Use case-

An application running behind an APIGateway. A test request is made from the APIGateway to the application, with the gateway attaching a trace id.

With the following code, the following error is logged and the trace id is not emitted as metadata on the corresponding logs-

```
Failed to extract span context: TraceHeaderParsingError(value: \"Root=X-XXXX\", reason: OpenTelemetryXRay.XRayPropagator.TraceHeaderParsingError.Reason.missingSampleDecision).
```

Doesn't look like the trace id coming from API Gateway has a sample decision.

**Comment by slashmo** [comment]
Interesting find, thanks for creating the issue 🙏 Reading the API gateway tracing docs it does look like it's not attaching the sampled flag at all 🤔 https://docs.aws.amazon.com/xray/latest/devguide/xray-services-apigateway.html

I looked at a couple of official OpenTelemetry implementations of `XRayPropagator` and it looks like they're all falling back to empty trace flags, i.e. _not sampled_, so I'd want to do the same in `swift-otel-xray`.

However, if you're using [`OTel.ParentBasedSampler`](https://swiftpackageindex.com/slashmo/swift-otel/0.7.0/documentation/opentelemetry/otel/parentbasedsampler) with an [`OTel.ConstantSampler`](https://swiftpackageindex.com/slashmo/swift-otel/0.7.0/documentation/opentelemetry/otel/constantsampler) as its [`remoteParentNotSampledSampler`](https://swiftpackageindex.com/slashmo/swift-otel/0.7.0/documentation/opentelemetry/otel/parentbasedsampler/init(rootsampler:remoteparentsampledsampler:remoteparentnotsampledsampler:localparentsampledsampler:localparentnotsampledsampler:)) this would mean that **your server spans would not be sampled**. You could work around this by setting a different, potentially custom, sampler as [`remoteParentNotSampledSampler`](https://swiftpackageindex.com/slashmo/swift-otel/0.7.0/documentation/opentelemetry/otel/parentbasedsampler/init(rootsampler:remoteparentsampledsampler:remoteparentnotsampledsampler:localparentsampledsampler:localparentnotsampledsampler:)).

Would this solve the issue for you?

## See Also 📖

- [OpenTelemetry Java: `AwsXrayPropagator`](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/7c205af4beedd4ec92d98405532079144685f7df/aws-xray-propagator/src/main/java/io/opentelemetry/contrib/awsxray/propagator/AwsXrayPropagator.java#L181)

**Comment by tachyonics** [comment]
From the small amount of reading I did, it looked like that was the correct behaviour so yes that would solve the issue, thanks!
